---
- hosts: 172.31.6.31
  become: yes
  tasks:
  - include_tasks: myfile.yml


  - name: i want to install apache2 server
    apt:
      name: apache2
      state: present
    notify: restartweb 

  - name: i want to copy j2 file on node ansible
    template:  
      src: index.j2
      dest: /var/www/html/index.html
  handlers:
   - name: restartweb
     service:
       name: apache2
       state: restarted
