---
- hosts: 172.31.6.31
  become: yes
  tasks:
  - include_tasks: myfile.yml


  - name: i want to install apache2 server
    apt:
      name: apache2
      state: present
  - name: i want to restart server
    service:
       name: apache2
       state: restarted