---
- hosts: webbrowser
  become: yes
  tasks:
  - include_tasks: myfile.yml


  - name: i want to install apache2 server
    apt:
      name: apache2
      state: present
  - name: i want to restart server
    service:
       name: apache2
       state: restarted

  - name: i want to copy j2 file on node ansible
    template:  
      src: index.j2
      dest: /var/www/html/index.html