---
- hosts: webbrowser
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install apache2 web server on my ubuntu
    apt:
        name: "{{myubuntu}}"
        state: present
    when: ansible_os_family =="Debian"
  - name: i want to install apache2 on webserver
    service:
     name: "{{myubuntu}}"
     state: started
    when: ansible_os_family =="Debian"
  - name: i want to install apache2 on redhat
    yum:
      name: "{{myredhat}}"
      state: present

    when: ansible_os_family =="RedHat"
  - name: i want to install webserver on RedHat
    service:
     name: "{{myredhat}}"
     state: started
    when: ansible_os_family =="RedHat"