---
- hosts: all
  become: yes
  gather_facts: nodes
  tasks:
   - name: i want to ping all nodes
     ping:
  
   - name: i want to install apache web server on my ubuntu
     apt:
       name: apache2 
       state: present
    
   - name: i want to install apache2 on redhat
     yum:
      name: httpd
      state: present