---
- name: create directory
  file:
    path: /opt/tomcat/bin
    state: directory
    mode: '0755'
- name: extract file
  command:
    cmd: tar xzvf /home/uduntu/apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE
